/**
 * 
 */
package com.adobe.prj.db.ddl;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import com.adobe.prj.dao.jdbc.DBUtil;

/**
 * @author danchara
 * 
 * Class for creating Employee table in database if one doesn't already exists.
 * 
 * Used in DbInit .
 *
 */
public class EmployeeDdl {
	public static void createEmployeeTable() {
		String createEmployeeTableSql = "CREATE TABLE IF NOT EXISTS employee ("+
								"id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1)PRIMARY KEY,"+
								"name VARCHAR(30) NOT NULL,"+
								"email  VARCHAR(50) NOT NULL,"+
								"role INTEGER NOT NULL);"; // 0 - STAFF , 1- MANAGER
								
		
		
	
	
		Connection connection = null;
		Statement statement = null;
		try {
			connection = DBUtil.getConnection();
			statement = connection.createStatement();
			statement.executeQuery(createEmployeeTableSql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			DBUtil.releaseStatement(statement);
			DBUtil.releaseConnection(connection);
		}
		
	}
	
	
}
