/**
 * 
 */
package com.adobe.prj.db.ddl;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import com.adobe.prj.dao.jdbc.DBUtil;

/**
 * @author danchara
 *
 *	Class for creating project table in database if one doesn't already exists.
 *	Used in DbInit .
 */
public class ProjectDdl {
	
	public static void createProjectTable(){
		String createProjectTableSql = "CREATE TABLE IF NOT EXISTS project ("+
				"id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1)PRIMARY KEY,"+
				"name VARCHAR(30) NOT NULL,"+
				"has_project_manager BOOLEAN DEFAULT FALSE NOT NULL);";
		
		
		Connection connection = null;
		Statement statement = null;
		try {
			connection = DBUtil.getConnection();
			statement = connection.createStatement();
			statement.executeQuery(createProjectTableSql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			DBUtil.releaseStatement(statement);
			DBUtil.releaseConnection(connection);
		}
		
		
		
	}
	
	
}
